using System.Collections.Generic;
using Microsoft.VisualBasic;

namespace NX_Macro_Controller_VxV;

internal static class KeyboardUtil
{
	private static Dictionary<string, string> _romajiMap;

	private static Dictionary<string, string> _modeMap;

	static KeyboardUtil()
	{
		_romajiMap = new Dictionary<string, string>();
		_modeMap = new Dictionary<string, string>();
		_romajiMap.Add("あ", "a");
		_romajiMap.Add("い", "i");
		_romajiMap.Add("う", "u");
		_romajiMap.Add("え", "e");
		_romajiMap.Add("お", "o");
		_romajiMap.Add("か", "ka");
		_romajiMap.Add("き", "ki");
		_romajiMap.Add("く", "ku");
		_romajiMap.Add("け", "ke");
		_romajiMap.Add("こ", "ko");
		_romajiMap.Add("さ", "sa");
		_romajiMap.Add("し", "si");
		_romajiMap.Add("す", "su");
		_romajiMap.Add("せ", "se");
		_romajiMap.Add("そ", "so");
		_romajiMap.Add("た", "ta");
		_romajiMap.Add("ち", "ti");
		_romajiMap.Add("つ", "tu");
		_romajiMap.Add("て", "te");
		_romajiMap.Add("と", "to");
		_romajiMap.Add("な", "na");
		_romajiMap.Add("に", "ni");
		_romajiMap.Add("ぬ", "nu");
		_romajiMap.Add("ね", "ne");
		_romajiMap.Add("の", "no");
		_romajiMap.Add("は", "ha");
		_romajiMap.Add("ひ", "hi");
		_romajiMap.Add("ふ", "hu");
		_romajiMap.Add("へ", "he");
		_romajiMap.Add("ほ", "ho");
		_romajiMap.Add("ま", "ma");
		_romajiMap.Add("み", "mi");
		_romajiMap.Add("む", "mu");
		_romajiMap.Add("め", "me");
		_romajiMap.Add("も", "mo");
		_romajiMap.Add("や", "ya");
		_romajiMap.Add("ゆ", "yu");
		_romajiMap.Add("よ", "yo");
		_romajiMap.Add("ら", "ra");
		_romajiMap.Add("り", "ri");
		_romajiMap.Add("る", "ru");
		_romajiMap.Add("れ", "re");
		_romajiMap.Add("ろ", "ro");
		_romajiMap.Add("わ", "wa");
		_romajiMap.Add("を", "wo");
		_romajiMap.Add("ん", "nn");
		_romajiMap.Add("が", "ga");
		_romajiMap.Add("ぎ", "gi");
		_romajiMap.Add("ぐ", "gu");
		_romajiMap.Add("げ", "ge");
		_romajiMap.Add("ご", "go");
		_romajiMap.Add("ざ", "za");
		_romajiMap.Add("じ", "zi");
		_romajiMap.Add("ず", "zu");
		_romajiMap.Add("ぜ", "ze");
		_romajiMap.Add("ぞ", "zo");
		_romajiMap.Add("だ", "da");
		_romajiMap.Add("ぢ", "di");
		_romajiMap.Add("づ", "du");
		_romajiMap.Add("で", "de");
		_romajiMap.Add("ど", "do");
		_romajiMap.Add("ば", "ba");
		_romajiMap.Add("び", "bi");
		_romajiMap.Add("ぶ", "bu");
		_romajiMap.Add("べ", "be");
		_romajiMap.Add("ぼ", "bo");
		_romajiMap.Add("ぱ", "pa");
		_romajiMap.Add("ぴ", "pi");
		_romajiMap.Add("ぷ", "pu");
		_romajiMap.Add("ぺ", "pe");
		_romajiMap.Add("ぽ", "po");
		_romajiMap.Add("ぁ", "la");
		_romajiMap.Add("ぃ", "li");
		_romajiMap.Add("ぅ", "lu");
		_romajiMap.Add("ぇ", "le");
		_romajiMap.Add("ぉ", "lo");
		_romajiMap.Add("ヵ", "lka");
		_romajiMap.Add("ヶ", "lki");
		_romajiMap.Add("っ", "ltu");
		_romajiMap.Add("ゃ", "lya");
		_romajiMap.Add("ゅ", "lyu");
		_romajiMap.Add("ょ", "lyo");
		_romajiMap.Add("ゎ", "lwa");
		_romajiMap.Add("\u3000", " ");
		_romajiMap.Add("＊", "*");
		_romajiMap.Add("＋", "+");
		_romajiMap.Add("：", ":");
		_romajiMap.Add("；", ";");
		_romajiMap.Add("\uff3e", "^");
		_romajiMap.Add("～", "~");
		_romajiMap.Add("＝", "=");
		_romajiMap.Add("ー", "-");
		_romajiMap.Add("！", "!");
		_romajiMap.Add("”", "\"");
		_romajiMap.Add("＃", "#");
		_romajiMap.Add("＄", "$");
		_romajiMap.Add("％", "%");
		_romajiMap.Add("＆", "&");
		_romajiMap.Add("’", "'");
		_romajiMap.Add("（", "(");
		_romajiMap.Add("）", ")");
		_romajiMap.Add("￥", "\\");
		_romajiMap.Add("｜", "|");
		_romajiMap.Add("「", "[");
		_romajiMap.Add("」", "]");
		_romajiMap.Add("｛", "{");
		_romajiMap.Add("｝", "}");
		_romajiMap.Add("＜", "<");
		_romajiMap.Add("＞", ">");
		_romajiMap.Add("、", ",");
		_romajiMap.Add("。", ".");
		_romajiMap.Add("・", "/");
		_romajiMap.Add("？", "?");
		_romajiMap.Add("\uff3f", "_");
		_romajiMap.Add("＠", "@");
		_romajiMap.Add("\uff40", "`");
		_modeMap.Add("あ", "HIRAGANA");
		_modeMap.Add("い", "HIRAGANA");
		_modeMap.Add("う", "HIRAGANA");
		_modeMap.Add("え", "HIRAGANA");
		_modeMap.Add("お", "HIRAGANA");
		_modeMap.Add("か", "HIRAGANA");
		_modeMap.Add("き", "HIRAGANA");
		_modeMap.Add("く", "HIRAGANA");
		_modeMap.Add("け", "HIRAGANA");
		_modeMap.Add("こ", "HIRAGANA");
		_modeMap.Add("さ", "HIRAGANA");
		_modeMap.Add("し", "HIRAGANA");
		_modeMap.Add("す", "HIRAGANA");
		_modeMap.Add("せ", "HIRAGANA");
		_modeMap.Add("そ", "HIRAGANA");
		_modeMap.Add("た", "HIRAGANA");
		_modeMap.Add("ち", "HIRAGANA");
		_modeMap.Add("つ", "HIRAGANA");
		_modeMap.Add("て", "HIRAGANA");
		_modeMap.Add("と", "HIRAGANA");
		_modeMap.Add("な", "HIRAGANA");
		_modeMap.Add("に", "HIRAGANA");
		_modeMap.Add("ぬ", "HIRAGANA");
		_modeMap.Add("ね", "HIRAGANA");
		_modeMap.Add("の", "HIRAGANA");
		_modeMap.Add("は", "HIRAGANA");
		_modeMap.Add("ひ", "HIRAGANA");
		_modeMap.Add("ふ", "HIRAGANA");
		_modeMap.Add("へ", "HIRAGANA");
		_modeMap.Add("ほ", "HIRAGANA");
		_modeMap.Add("ま", "HIRAGANA");
		_modeMap.Add("み", "HIRAGANA");
		_modeMap.Add("む", "HIRAGANA");
		_modeMap.Add("め", "HIRAGANA");
		_modeMap.Add("も", "HIRAGANA");
		_modeMap.Add("や", "HIRAGANA");
		_modeMap.Add("ゆ", "HIRAGANA");
		_modeMap.Add("よ", "HIRAGANA");
		_modeMap.Add("ら", "HIRAGANA");
		_modeMap.Add("り", "HIRAGANA");
		_modeMap.Add("る", "HIRAGANA");
		_modeMap.Add("れ", "HIRAGANA");
		_modeMap.Add("ろ", "HIRAGANA");
		_modeMap.Add("わ", "HIRAGANA");
		_modeMap.Add("を", "HIRAGANA");
		_modeMap.Add("ん", "HIRAGANA");
		_modeMap.Add("が", "HIRAGANA");
		_modeMap.Add("ぎ", "HIRAGANA");
		_modeMap.Add("ぐ", "HIRAGANA");
		_modeMap.Add("げ", "HIRAGANA");
		_modeMap.Add("ご", "HIRAGANA");
		_modeMap.Add("ざ", "HIRAGANA");
		_modeMap.Add("じ", "HIRAGANA");
		_modeMap.Add("ず", "HIRAGANA");
		_modeMap.Add("ぜ", "HIRAGANA");
		_modeMap.Add("ぞ", "HIRAGANA");
		_modeMap.Add("だ", "HIRAGANA");
		_modeMap.Add("ぢ", "HIRAGANA");
		_modeMap.Add("づ", "HIRAGANA");
		_modeMap.Add("で", "HIRAGANA");
		_modeMap.Add("ど", "HIRAGANA");
		_modeMap.Add("ば", "HIRAGANA");
		_modeMap.Add("び", "HIRAGANA");
		_modeMap.Add("ぶ", "HIRAGANA");
		_modeMap.Add("べ", "HIRAGANA");
		_modeMap.Add("ぼ", "HIRAGANA");
		_modeMap.Add("ぱ", "HIRAGANA");
		_modeMap.Add("ぴ", "HIRAGANA");
		_modeMap.Add("ぷ", "HIRAGANA");
		_modeMap.Add("ぺ", "HIRAGANA");
		_modeMap.Add("ぽ", "HIRAGANA");
		_modeMap.Add("ぁ", "HIRAGANA");
		_modeMap.Add("ぃ", "HIRAGANA");
		_modeMap.Add("ぅ", "HIRAGANA");
		_modeMap.Add("ぇ", "HIRAGANA");
		_modeMap.Add("ぉ", "HIRAGANA");
		_modeMap.Add("ヵ", "KATAKANA");
		_modeMap.Add("ヶ", "KATAKANA");
		_modeMap.Add("っ", "HIRAGANA");
		_modeMap.Add("ゃ", "HIRAGANA");
		_modeMap.Add("ゅ", "HIRAGANA");
		_modeMap.Add("ょ", "HIRAGANA");
		_modeMap.Add("ゎ", "HIRAGANA");
		_modeMap.Add("\u3000", "HIRAGANA");
		_modeMap.Add("＊", "HIRAGANA");
		_modeMap.Add("＋", "HIRAGANA");
		_modeMap.Add("：", "HIRAGANA");
		_modeMap.Add("；", "HIRAGANA");
		_modeMap.Add("\uff3e", "HIRAGANA");
		_modeMap.Add("～", "HIRAGANA");
		_modeMap.Add("＝", "HIRAGANA");
		_modeMap.Add("ー", "HIRAGANA");
		_modeMap.Add("！", "HIRAGANA");
		_modeMap.Add("”", "HIRAGANA");
		_modeMap.Add("＃", "HIRAGANA");
		_modeMap.Add("＄", "HIRAGANA");
		_modeMap.Add("％", "HIRAGANA");
		_modeMap.Add("＆", "HIRAGANA");
		_modeMap.Add("’", "HIRAGANA");
		_modeMap.Add("（", "HIRAGANA");
		_modeMap.Add("）", "HIRAGANA");
		_modeMap.Add("￥", "HIRAGANA");
		_modeMap.Add("｜", "HIRAGANA");
		_modeMap.Add("「", "HIRAGANA");
		_modeMap.Add("」", "HIRAGANA");
		_modeMap.Add("｛", "HIRAGANA");
		_modeMap.Add("｝", "HIRAGANA");
		_modeMap.Add("＜", "HIRAGANA");
		_modeMap.Add("＞", "HIRAGANA");
		_modeMap.Add("、", "HIRAGANA");
		_modeMap.Add("。", "HIRAGANA");
		_modeMap.Add("・", "HIRAGANA");
		_modeMap.Add("？", "HIRAGANA");
		_modeMap.Add("\uff3f", "HIRAGANA");
		_modeMap.Add("＠", "HIRAGANA");
		_modeMap.Add("\uff40", "HIRAGANA");
		_modeMap.Add("ア", "KATAKANA");
		_modeMap.Add("イ", "KATAKANA");
		_modeMap.Add("ウ", "KATAKANA");
		_modeMap.Add("エ", "KATAKANA");
		_modeMap.Add("オ", "KATAKANA");
		_modeMap.Add("カ", "KATAKANA");
		_modeMap.Add("キ", "KATAKANA");
		_modeMap.Add("ク", "KATAKANA");
		_modeMap.Add("ケ", "KATAKANA");
		_modeMap.Add("コ", "KATAKANA");
		_modeMap.Add("サ", "KATAKANA");
		_modeMap.Add("シ", "KATAKANA");
		_modeMap.Add("ス", "KATAKANA");
		_modeMap.Add("セ", "KATAKANA");
		_modeMap.Add("ソ", "KATAKANA");
		_modeMap.Add("タ", "KATAKANA");
		_modeMap.Add("チ", "KATAKANA");
		_modeMap.Add("ツ", "KATAKANA");
		_modeMap.Add("テ", "KATAKANA");
		_modeMap.Add("ト", "KATAKANA");
		_modeMap.Add("ナ", "KATAKANA");
		_modeMap.Add("ニ", "KATAKANA");
		_modeMap.Add("ヌ", "KATAKANA");
		_modeMap.Add("ネ", "KATAKANA");
		_modeMap.Add("ノ", "KATAKANA");
		_modeMap.Add("ハ", "KATAKANA");
		_modeMap.Add("ヒ", "KATAKANA");
		_modeMap.Add("フ", "KATAKANA");
		_modeMap.Add("ヘ", "KATAKANA");
		_modeMap.Add("ホ", "KATAKANA");
		_modeMap.Add("マ", "KATAKANA");
		_modeMap.Add("ミ", "KATAKANA");
		_modeMap.Add("ム", "KATAKANA");
		_modeMap.Add("メ", "KATAKANA");
		_modeMap.Add("モ", "KATAKANA");
		_modeMap.Add("ヤ", "KATAKANA");
		_modeMap.Add("ユ", "KATAKANA");
		_modeMap.Add("ヨ", "KATAKANA");
		_modeMap.Add("ラ", "KATAKANA");
		_modeMap.Add("リ", "KATAKANA");
		_modeMap.Add("ル", "KATAKANA");
		_modeMap.Add("レ", "KATAKANA");
		_modeMap.Add("ロ", "KATAKANA");
		_modeMap.Add("ワ", "KATAKANA");
		_modeMap.Add("ヲ", "KATAKANA");
		_modeMap.Add("ン", "KATAKANA");
		_modeMap.Add("ガ", "KATAKANA");
		_modeMap.Add("ギ", "KATAKANA");
		_modeMap.Add("グ", "KATAKANA");
		_modeMap.Add("ゲ", "KATAKANA");
		_modeMap.Add("ゴ", "KATAKANA");
		_modeMap.Add("ザ", "KATAKANA");
		_modeMap.Add("ジ", "KATAKANA");
		_modeMap.Add("ズ", "KATAKANA");
		_modeMap.Add("ゼ", "KATAKANA");
		_modeMap.Add("ゾ", "KATAKANA");
		_modeMap.Add("ダ", "KATAKANA");
		_modeMap.Add("ヂ", "KATAKANA");
		_modeMap.Add("ヅ", "KATAKANA");
		_modeMap.Add("デ", "KATAKANA");
		_modeMap.Add("ド", "KATAKANA");
		_modeMap.Add("バ", "KATAKANA");
		_modeMap.Add("ビ", "KATAKANA");
		_modeMap.Add("ブ", "KATAKANA");
		_modeMap.Add("ベ", "KATAKANA");
		_modeMap.Add("ボ", "KATAKANA");
		_modeMap.Add("パ", "KATAKANA");
		_modeMap.Add("ピ", "KATAKANA");
		_modeMap.Add("プ", "KATAKANA");
		_modeMap.Add("ペ", "KATAKANA");
		_modeMap.Add("ポ", "KATAKANA");
		_modeMap.Add("ァ", "KATAKANA");
		_modeMap.Add("ィ", "KATAKANA");
		_modeMap.Add("ゥ", "KATAKANA");
		_modeMap.Add("ェ", "KATAKANA");
		_modeMap.Add("ォ", "KATAKANA");
		_modeMap.Add("ッ", "KATAKANA");
		_modeMap.Add("ャ", "KATAKANA");
		_modeMap.Add("ュ", "KATAKANA");
		_modeMap.Add("ョ", "KATAKANA");
		_modeMap.Add("ヮ", "KATAKANA");
	}

	internal static string RomajiConvert(string hiragana)
	{
		hiragana = Strings.StrConv(hiragana, VbStrConv.Hiragana, 1041);
		string text = "";
		string text2 = hiragana;
		for (int i = 0; i < text2.Length; i++)
		{
			char c = text2[i];
			string value = "";
			bool flag = _romajiMap.TryGetValue(c.ToString(), out value);
			text += (flag ? value : c.ToString());
		}
		return text;
	}

	internal static string RomajiConvert(char c)
	{
		string text = Strings.StrConv(c.ToString(), VbStrConv.Hiragana, 1041);
		string value = "";
		if (!_romajiMap.TryGetValue(text, out value))
		{
			return text;
		}
		return value;
	}

	internal static string GetInputMode(char c)
	{
		string value = "ALPHANUMERIC";
		if (!_modeMap.TryGetValue(c.ToString(), out value))
		{
			return "ALPHANUMERIC";
		}
		return value;
	}
}
